insert into theme(theme) values ('Reportaż');
insert into theme(theme) values ('Historia');
insert into theme(theme) values ('S-F');
insert into theme(theme) values ('Futbol');
insert into theme(theme) values ('IT');
insert into theme(theme) values ('Sensacja');
insert into theme(theme) values ('Kryminał');
insert into theme(theme) values ('Fantasy');
insert into theme(theme) values ('Historical fiction');
insert into theme(theme) values ('Dziecko');
insert into theme(theme) values ('Bieganie');
insert into theme(theme) values ('Kolarstwo');
insert into theme(theme) values ('Selfdev');
insert into theme(theme) values ('Horror');
insert into theme(theme) values ('Finanse');