insert into book (author, locations, title, theme_id) values ('Andrzej Sapkowski', 123, 'Wiedźmin: Sezon burz', 8);
insert into book (author, locations, title, theme_id) values ('Zygmunt Miłoszewski', 5033, 'Uwikłanie', 7);
insert into book (author, locations, title, theme_id) values ('Jo Nesbo', 9142, 'Czerwone gardło', 7);
insert into book (author, locations, title, theme_id) values ('Zygmunt Miłoszewski', 6306, 'Gniew', 7);
insert into book (author, locations, title, theme_id) values ('Mariusz Czubaj', 3977, 'Postfutbol', 4);
insert into book (author, locations, title, theme_id) values ('Philip Dick', 4487, 'Człowiek z wysokiego zamku', 9);
insert into book (author, locations, title, theme_id) values ('Jacek Dukaj', 22611, 'Lód', 8);
insert into book (author, locations, title, theme_id) values ('Frederic Pichon', 1614, 'Syria. Porażka strategii Zachodu', 1);
insert into book (author, locations, title, theme_id) values ('Rolf Bauerdick', 4855, 'Cyganie. Spotkania z nielubianym narodem', 1);
insert into book (author, locations, title, theme_id) values ('Marek Kęskrawiec', 4600, 'Czwarty pożar Teheranu', 1);
insert into book (author, locations, title, theme_id) values ('Aldous Huxley', 3417, 'Nowy wspaniały świat', 9);
insert into book (author, locations, title, theme_id) values ('Michał Okoński', 3178, 'Futbol jest okrutny', 4);
insert into book (author, locations, title, theme_id) values ('Jacek Hugo-Bader', 5777, 'Biała gorączka', 1);
insert into book (author, locations, title, theme_id) values ('Jacek Hugo-Bader', 5896, 'W rajskiej dolinie wśród zielska', 1);
insert into book (author, locations, title, theme_id) values ('Gina Ford', 4299, 'Pierwszy rok życia dziecka', 10);
insert into book (author, locations, title, theme_id) values ('Stefan Szymański, Simon Kuper', 9243, 'Futbonomia', 4);
insert into book (author, locations, title, theme_id) values ('Tom Clancy', 10001, 'Wektor zagrożenia', 6);
insert into book (author, locations, title, theme_id) values ('Elżbieta Cherezińska', 13739, 'Korona śniegu i krwi', 2);
insert into book (author, locations, title, theme_id) values ('Jarosław Grzędowicz', 5878, 'Księga jesiennych demonów', 8);
insert into book (author, locations, title, theme_id) values ('Jarosław Grzędowicz', 6079, 'Hel 3', 3);
insert into book (author, locations, title, theme_id) values ('Brandon Sanderson', 20765, 'Droga królów', 8);
insert into book (author, locations, title, theme_id) values ('Orson Scott Card', 5518, 'Siódmy syn', 8);
insert into book (author, locations, title, theme_id) values ('Orson Scott Card', 6167, 'Czerwony prorok', 8);
insert into book (author, locations, title, theme_id) values ('Orson Scott Card', 7015, 'Uczeń Alvin', 8);
insert into book (author, locations, title, theme_id) values ('Travis Macy', 3990, 'Ultranastawienie', 11);
insert into book (author, locations, title, theme_id) values ('Orson Scott Card', 8104, 'Alvin czeladnik', 8);
insert into book (author, locations, title, theme_id) values ('Richard Moore', 5681, 'Tour de France. Etapy, które przeszły do historii', 12);
insert into book (author, locations, title, theme_id) values ('Wiktor Suworow', 4367, 'Specnaz', 2);
insert into book (author, locations, title, theme_id) values ('Wiktor Suworow', 5834, 'Lodołamacz', 2);
insert into book (author, locations, title, theme_id) values ('Wiktor Suworow', 5577, 'Samobójstwo', 2);
insert into book (author, locations, title, theme_id) values ('Terry Pratchett', 4078, 'Mort', 8);
insert into book (author, locations, title, theme_id) values ('Charles Duhigg', 6737, 'Siła nawyku', 13);
insert into book (author, locations, title, theme_id) values ('Jarosław Grzędowicz', 6234, 'Pan Lodowego Ogrodu - tom 1', 8);
insert into book (author, locations, title, theme_id) values ('Jarosław Grzędowicz', 7347, 'Pan Lodowego Ogrodu - tom 2', 8);
insert into book (author, locations, title, theme_id) values ('Jarosław Grzędowicz', 5829, 'Pan Lodowego Ogrodu - tom 3', 8);
insert into book (author, locations, title, theme_id) values ('Jarosław Grzędowicz', 10821, 'Pan Lodowego Ogrodu - tom 4', 8);
insert into book (author, locations, title, theme_id) values ('Pete Goodliffe', 6418, 'Jak stać się lepszym programistą', 5);
insert into book (author, locations, title, theme_id) values ('Federico Bianuzzi', 13966, 'Wielkie umysły programowania. Jak myślą i pracują twórcy najważniejszych języków', 5);
insert into book (author, locations, title, theme_id) values ('Douglas Boyd', 6975, 'Ekspansja Kremla', 2);
insert into book (author, locations, title, theme_id) values ('Frank Herbert', 11414, 'Diuna', 3);
insert into book (author, locations, title, theme_id) values ('Jo Nesbo', 6758, 'Człowiek nietoperz', 7);
insert into book (author, locations, title, theme_id) values ('Neil Fiore', 3689, 'Nawyk samodyscypliny. Zaprogramuj wewnętrznego stróża', 13);
insert into book (author, locations, title, theme_id) values ('Greg Jenner', 5821, 'Milion lat w jeden dzień', 2);
insert into book (author, locations, title, theme_id) values ('Victor Frankl', 2360, 'Człowiek w poszukiwaniu sensu', 13);
insert into book (author, locations, title, theme_id) values ('Gayle Laakmann McDowell', 21587, 'Rozmowa rekrutacyjna dla programistów', 5);
insert into book (author, locations, title, theme_id) values ('Craig Walls', 22383, 'Spring w akcji. Wydane IV', 5);
insert into book (author, locations, title, theme_id) values ('Michał Bartyzel', 2873, 'Getting things programmed. Droga do efektywności', 5);
insert into book (author, locations, title, theme_id) values ('Robert J. Szmidt', 5586, 'Łatwo być Bogiem', 3);
insert into book (author, locations, title, theme_id) values ('William Poundsone', 4780, 'Czy jesteś wystarczająco bystry, żeby pracować w Google?', 5);
insert into book (author, locations, title, theme_id) values ('Peter Seibel', 11612, 'Sztuka kodowania. Sekrety wielkich programistów', 5);
insert into book (author, locations, title, theme_id) values ('Jason Price', 32323, 'Oracle Database 12c i SQL. Programowanie', 5);
insert into book (author, locations, title, theme_id) values ('Isaac Asimov', 4447, 'Ja, robot', 3);
insert into book (author, locations, title, theme_id) values ('Richard Nisbett', 6648, 'Mindware. Narzędzia skutecznego myślenia', 13);
insert into book (author, locations, title, theme_id) values ('Erik Bertrand Larrsen', 3430, 'Bez litości', 13);
insert into book (author, locations, title, theme_id) values ('Ion Mihai Pacepa', 11055, 'Dezinformacja', 2);
insert into book (author, locations, title, theme_id) values ('Steven Johnson', 3504, 'Małe wielkie odkrycia', 2);
insert into book (author, locations, title, theme_id) values ('Marek Wałkuski', 5440, 'Wałkowanie Ameryki', 1);
insert into book (author, locations, title, theme_id) values ('Andrew Tanenbaum', 36374, 'Systemy operacyjne. Wydanie IV', 5);
insert into book (author, locations, title, theme_id) values ('Steve Scott', 1704, 'Piętrzenie nawyków. 97 małych zmian, które odmienią Twoje życie', 13);
insert into book (author, locations, title, theme_id) values ('Brian Tracy', 4470, 'Nie tłumacz się, działaj! Odkryj moc samodyscypliny', 13);
insert into book (author, locations, title, theme_id) values ('Bryan Basham', 0, 'Head First: Servlets JSP', 5);
insert into book (author, locations, title, theme_id) values ('Eric Freeman', 0, 'Head First: Wzorce projektowe', 5);
insert into book (author, locations, title, theme_id) values ('Scott Galloway', 5046, 'Wielka czwórka. Ukryte DNA: Amazon, Apple, Facebook i Google', 5);
insert into book (author, locations, title, theme_id) values ('Gene Kim', 7998, 'Projekt Feniks. Powieść o IT, modelu DevOps i o tym, jak pomóc firmie w odniesieniu sukcesu', 5);
insert into book (author, locations, title, theme_id) values ('Joshua Bloch', 20392, 'Java. Efektywne programowanie. Wydanie III', 5);
insert into book (author, locations, title, theme_id) values ('Michael Cox', 7723, 'Premier League. Historia taktyki w najlepszej piłkarskiej lidze świata', 4);
insert into book (author, locations, title, theme_id) values ('James Warren', 9534, 'Big Data. Najlepsze praktyki budowy skalowalnych systemów obsługi danych w czasie rzeczywistym', 5);
insert into book (author, locations, title, theme_id) values ('Evi Nemeth', 45331, 'Unix i Linux. Przewodnik administratora', 5);
insert into book (author, locations, title, theme_id) values ('Ziemowit Ochapski', 4795, 'Ronaldo - fenomen z Brazylii', 4);
insert into book (author, locations, title, theme_id) values ('Łukasz Grass', 3874, 'Najlepszy', 11);
insert into book (author, locations, title, theme_id) values ('Charles Duhigg', 7287, 'Mądrzej, szybciej, lepiej', 13);
insert into book (author, locations, title, theme_id) values ('Neil Fiore', 2759, 'Nawyk samodyscypliny w pracy', 13);
insert into book (author, locations, title, theme_id) values ('Stephen King', 21616, 'To', 14);
insert into book (author, locations, title, theme_id) values ('Judyta Watoła', 4085, 'Słodziutki', 2);
insert into book (author, locations, title, theme_id) values ('Kasper van der Maulen', 3014, 'Mindlift: mental fitness for the modern mind', 13);
insert into book (author, locations, title, theme_id) values ('Gynvael Coldwind', 12552, 'Zrozumieć programowanie', 5);
insert into book (author, locations, title, theme_id) values ('Amy McCready', 4790, 'Dziecko, czy muszę ci to jeszcze raz powtarzać?', 10);
insert into book (author, locations, title, theme_id) values ('Max Kanat-Alexander', 2770, 'Understanding software', 5);
insert into book (author, locations, title, theme_id) values ('Michał Szafrański', 14266, 'Finansowy ninja', 13);
insert into book (author, locations, title, theme_id) values ('Gretchen Rubin', 5047, 'Lepiej, 21 strategii, by osiągnąć szczęście', 13);
insert into book (author, locations, title, theme_id) values ('Frederick P. Brooks Jr', 5413, 'Legendarny osobomiesiąc. Opowieść o inżynierii oprogramowania', 5);
insert into book (author, locations, title, theme_id) values ('David Rock', 5614, 'Twój mózg w działaniu', 13);
insert into book (author, locations, title, theme_id) values ('William Ury', 2191, 'Dochodząc do tak ze sobą', 13);
insert into book (author, locations, title, theme_id) values ('John Sonmez', 9086, 'Sprawny programista. Pracuj, zarabiaj i zdobywaj kwalifikacje.', 13);
insert into book (author, locations, title, theme_id) values ('Marcin Mortka', 17553, 'Miecz i kwiaty', 8);
insert into book (author, locations, title, theme_id) values ('Victor Davich', 2649, '8 minut medytacji. Spokój umysłu na co dzień.', 13);
insert into book (author, locations, title, theme_id) values ('Robert Sedgewick', 2649, 'Algorytmy. Wydanie IV', 5);
insert into book (author, locations, title, theme_id) values ('Ryszard Tadeusiewicz', 3910, 'Krótka historia informatyki', 5);
insert into book (author, locations, title, theme_id) values ('Mariusz Szuba', 1051, 'Legalny doping emocjonalny', 13);
insert into book (author, locations, title, theme_id) values ('Pramod J. Sadalage, Martin Fowler', 3765, 'NoSQL. Kompendium wiedzy', 5);
insert into book (author, locations, title, theme_id) values ('Trudi Canavan', 6614, 'Gildia magów', 8);
insert into book (author, locations, title, theme_id) values ('Michael Lennington, Brian P. Moran', 3514, '12-tygodniowy rok. Osiągnij w 12 tygodni więcej niż inni w 12 miesięcy.', 13);
insert into book (author, locations, title, theme_id) values ('Bartosz Kulisz', 80, 'Twoja hierarchia wartości', 13);
insert into book (author, locations, title, theme_id) values ('Michael Calvin', 4609, 'Ludzie znikąd. Nieprzenikniony świat skautów piłkarskich', 4);
insert into book (author, locations, title, theme_id) values ('Pat Flynn', 3991, 'Gotowi na start. Jak sprawdzić pomysł na biznes, żeby nie stracić czasu i pieniędzy', 13);
insert into book (author, locations, title, theme_id) values ('Marcin Feddek', 7123, 'Dekalog Nawałki', 4);
insert into book (author, locations, title, theme_id) values ('Jared Diamond', 10834, 'Strzelby, zarazki i stal. Krótka historia ludzkości', 2);
insert into book (author, locations, title, theme_id) values ('T. Harv Eker', 3069, 'Bogaty albo biedny. Po prostu różni mentalnie', 13);
insert into book (author, locations, title, theme_id) values ('Niels Lunde', 6393, 'Lego. Jak pokonać kryzys, zawojować świat i zbudować potęgę z klocków.', 2);
insert into book (author, locations, title, theme_id) values ('Rafael Santandreu', 3200, 'Wszystko jest łatwiejsze niż nam się wydaje.', 13);
insert into book (author, locations, title, theme_id) values ('David Sumpter', 5302, 'Piłkomatyka. Matematyczne piękno futbolu', 4);
insert into book (author, locations, title, theme_id) values ('Scott Young', 4586, 'Zostań ultrasamoukiem. Jak mistrzowsko opanować twarde umiejętności w zadziwiająco krótkim czasie.', 13);
insert into book (author, locations, title, theme_id) values ('James Clear', 4762, 'Atomowe nawyki', 13);
insert into book (author, locations, title, theme_id) values ('Ronald Reng', 7259, 'Bundesliga. Niezwykła opowieść o niemieckim futbolu', 4);
insert into book (author, locations, title, theme_id) values ('Jesper Juul', 0, 'O granicach. Kompetentne relacje z dzieckiem', 13);
insert into book (author, locations, title, theme_id) values ('David Lagercrantz', 7037, 'Co nas nie zabije', 6);
insert into book (author, locations, title, theme_id) values ('David Lagercrantz', 5604, 'Mężczyzna, który gonił swój cień', 6);
insert into book (author, locations, title, theme_id) values ('Brian W. Kernighan', 3990, 'Jak Unix tworzył historię', 5);
insert into book (author, locations, title, theme_id) values ('Ken Follett', 6799, 'Lot ćmy', 6);
insert into book (author, locations, title, theme_id) values ('Elton Stoneman', 12928, 'Nauka Dockera w miesiąc', 5);
insert into book (author, locations, title, theme_id) values ('Elton Stoneman', 17125, 'Nauka Kubernetesa w miesiąc', 5);
insert into book (author, locations, title, theme_id) values ('Blake J. Harris', 10291, 'Wojny konsolowe', 2);
insert into book (author, locations, title, theme_id) values ('Marek Kądzielski', 3514, 'Wolny strzelec', 16);
insert into book (author, locations, title, theme_id) values ('J. Siegel, Tina Payne-Bryson', 2386, 'The Yes Brain. Mózg na tak', 10);
insert into book (author, locations, title, theme_id) values ('Jacek Ponikiewski', 1283, 'DNA stresu', 13);
insert into book (author, locations, title, theme_id) values ('Agnieszka Kozak, Jacek Wasilewski', 5507, 'Uwięzieni w słowach rodziców. Jak uwolnić się od zaklęć, które rzucono na nas w dzieciństwie', 10);
insert into book (author, locations, title, theme_id) values ('Ilona Wiśniewska', 2915, 'Migot', 1);
insert into book (author, locations, title, theme_id) values ('Andrea Camilleri', 3941, 'Głosy nocy', 7);
insert into book (author, locations, title, theme_id) values ('Krzysztof Kotowski', 2862, 'Krew snajperów', 1);
insert into book (author, locations, title, theme_id) values ('Przemysław Waingertner', 3507, 'Czwarta stolica. Kiedy Łódź rządziła Polską', 2);
insert into book (author, locations, title, theme_id) values ('Jacek Komuda', 8390, 'Galeony wojny', 8);
insert into book (author, locations, title, theme_id) values ('Jason Schreier', 4503, 'Krew, pot i piksele. Chwalebne i niepokojące opowieści o tym, jak robi się gry.', 2);
insert into book (author, locations, title, theme_id) values ('Christoph Biermann', 5451, 'Piłkarscy hakerzy. O rewolucji w futbolu i sztuce zbierania danych.', 4);
insert into book (author, locations, title, theme_id) values ('Michael Cox', 6992, 'Gegenpressing i tiki-taka. Jak rodził się nowoczesny europejski futbol.', 4);
insert into book (author, locations, title, theme_id) values ('Soumen Chatterjee', 3626, 'Google Cloud Certified Professional Cloud Architect. Wprowadzenie do platformy i materiały egzaminacyjne. Wydanie II', 5);
insert into book (author, locations, title, theme_id) values ('Marie Taylor. Steve Crabb', 10535, 'Coaching i mentoring biznesowy dla bystrzaków', 13);
insert into book (author, locations, title, theme_id) values ('Tony Buzan', 2837, 'Mistrzowskie mapowanie myśli', 13);
insert into book (author, locations, title, theme_id) values ('Marta Iwanowska-Polkowska', 5192, 'Nażyć się', 13);
insert into book (author, locations, title, theme_id) values ('Katarzyna Gubała', 2348, 'Wege energia', 17);
insert into book (author, locations, title, theme_id) values ('Daniel Zingaro', 14048, 'Myślenie algorytmiczne. Jak rozwiązywać problemy za pomocą algorytmów', 5);
insert into book (author, locations, title, theme_id) values ('Jacek Komuda', 6671, 'Westerplatte', 8);
insert into book (author, locations, title, theme_id) values ('Sid Meier', 4572, 'Wspomnienia. Oficjalna autobiografia twórcy Cywilizacji', 5);
insert into book (author, locations, title, theme_id) values ('Chris Riccomini, Dmitriy Ryaboy', 246, 'Brakujący plik Readme', 5);
insert into book (author, locations, title, theme_id) values ('Piotr Kościelny', 5636, 'Dom', 7);
insert into book (author, locations, title, theme_id) values ('Krystyna Kurczab-Redlich', 10525, 'Głową o mur Kremla', 1);
insert into book (author, locations, title, theme_id) values ('Grzegorz Mnich', 4166, 'Stalinowska codzienność. Łódź w latach 1949 - 1956', 2);
insert into book (author, locations, title, theme_id) values ('Ken Follett', 12771, 'Niech stanie się światłość', 9);
insert into book (author, locations, title, theme_id) values ('Krzysztof Lesiakowski', 5980, 'Gomułkowska rzeczywistość. Łódź w latach 1956 - 1970', 2);
insert into book (author, locations, title, theme_id) values ('Janusz Gudowski', 2406, 'W poprzek kultur', 1);
insert into book (author, locations, title, theme_id) values ('Witold Jarno', 5111, 'Gierkowska prosperita. Łódź w latach 1971 - 1980', 2);
insert into book (author, locations, title, theme_id) values ('Leszek Olejnik', 6772, 'Dekada Solidarności. Łódź w latach 1980 - 1989', 2);
insert into book (author, locations, title, theme_id) values ('Bogusław Politowski', 2863, '5/25 Saperzy w strefie śmierci', 1);
insert into book (author, locations, title, theme_id) values ('Titus Winters, Tom Manshreck, Hyrum Wright', 16568, 'Inżynieria oprogramowania według Google', 5);
insert into book (author, locations, title, theme_id) values ('Michał Zachodny', 4409, 'Polska myśl szkoleniowa', 4);
insert into book (author, locations, title, theme_id) values ('Matt Krantz', 9400, 'Analiza fundamentalna dla bystrzaków', 15);
insert into book (author, locations, title, theme_id) values ('Ewa Sapieżyńska', 1790, 'Nie jestem twoim Polakiem', 1);
insert into book (author, locations, title, theme_id) values ('Barbara Lech', 3600, 'Kiedy odwlekasz i narzekasz... 102 sposoby na pokonanie prokrastynacji', 13);
insert into book (author, locations, title, theme_id) values ('Piotr Marecki, Tomasz Tdc Cieślewicz', 4098, 'Oni migają tymi kolorami w sposób profesjonalny. Narodziny gamedevu z ducha demosceny w Polsce', 5);
insert into book (author, locations, title, theme_id) values ('Tomas Forro', 4045, 'Gorączka złota. Jak upadała Wenezuela', 1);
insert into book (author, locations, title, theme_id) values ('Wojciech Górecki, Bartosz Józefiak', 5156, 'Łódź. Miasto po przejściach', 1);
insert into book (author, locations, title, theme_id) values ('Doug Sillars', 5393, 'High Performance Android Apps', 5);
insert into book (author, locations, title, theme_id) values ('Chet Haase', 9108, 'Androidy: Zespół, który stworzył system operacyjny Android', 5);
insert into book (author, locations, title, theme_id) values ('Bill Aulet', 5387, 'Przedsiębiorczość zdyscyplinowana. Od startupu do sukcesu w 24 krokach', 16);
insert into book (author, locations, title, theme_id) values ('Patrick Lencioni', 2423, 'Pięć dysfunkcji pracy zespołowej. Opowieść o przywództwie', 16);
insert into book (author, locations, title, theme_id) values ('Patrick Lencioni', 3053, 'Trzy oznaki pracy, która nie daje szczęścia. Opowieść o przywództwie', 16);
insert into book (author, locations, title, theme_id) values ('Jeremy Kubica', 7424, 'Struktury danych z przymrużeniem oka. Zabawna przygoda z przykładami pachnącymi kawą', 5);
insert into book (author, locations, title, theme_id) values ('Kevin Trudeau', 7182, 'Superpamięć. Trening z Kevinem Trudeau', 13);
insert into book (author, locations, title, theme_id) values ('Alicja Grzesiak', 6896, 'Zatroszcz się o swoje wewnętrzne dziecko i odkryj swój potencjał', 10);
insert into book (author, locations, title, theme_id) values ('Igor Ryżow', 3248, 'Negocjacje z potworami. Jak osiągnąć to, co chcemy negocjując z silniejszymi od siebie', 13);
insert into book (author, locations, title, theme_id) values ('Sławek Gortych', 5731, 'Schronisko, które przestało istnieć', 7);
